import type { Metadata } from "next";
import { MainDock } from "./components/dock";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LightRays } from "@/components/ui/light-rays";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#fbfefb] dark:bg-[#0d1321] text-black dark:text-white transition-colors duration-500 relative min-h-screen`}
      >
        <div className="fixed inset-0 z-0 pointer-events-none">
          <LightRays color="var(--ray-color)" length="100vh" count={5} />
        </div>

        <div className="relative z-10">{children}</div>

        <MainDock />
      </body>
    </html>
  );
}
