import type { Metadata } from "next";
import { MainDock } from "@/components/PortfolioDock";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import { ProgressiveBlur } from "@/components/ui/progressive-blur";
import { LightRays } from "@/components/ui/light-rays";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-background text-black dark:text-white transition-colors duration-500 relative min-h-screen overflow-hidden`}
      >
        <SmoothCursor />
        <div className="fixed inset-0 z-0 pointer-events-none">
          <LightRays color="var(--ray-color)" length="100vh" count={5} />
        </div>

        <div className="font-sans relative z-10 h-screen w-full">
          {children}
        </div>

        <MainDock />
        <ProgressiveBlur height="30%" position="bottom" />
      </body>
    </html>
  );
}
